import { Permisos } from "../types";

export const INICIALES: Permisos = {
  ver: {
    usuario: false,
    restauracion: false,
    cliente: false,
    mensaje: false,
    ticket: false,
    categoría: false,
    imagen: false,
    venta: false,
    compra: false,
    publicación: false,
    proveedor: false,
    reporte: false,
    mensajería: false,
    producto: false,
    impuesto: false,
    rol: false,
  },
  crear: {
    usuario: false,
    restauracion: false,
    cliente: false,
    mensaje: false,
    ticket: false,
    categoría: false,
    imagen: false,
    venta: false,
    compra: false,
    publicación: false,
    proveedor: false,
    reporte: false,
    mensajería: false,
    producto: false,
    impuesto: false,
    rol: false,
  },
  editar: {
    usuario: false,
    restauracion: false,
    cliente: false,
    mensaje: false,
    ticket: false,
    categoría: false,
    imagen: false,
    venta: false,
    compra: false,
    publicación: false,
    proveedor: false,
    reporte: false,
    mensajería: false,
    producto: false,
    impuesto: false,
    rol: false,
  },
  eliminar: {
    usuario: false,
    restauracion: false,
    cliente: false,
    mensaje: false,
    ticket: false,
    categoría: false,
    imagen: false,
    venta: false,
    compra: false,
    publicación: false,
    proveedor: false,
    reporte: false,
    mensajería: false,
    producto: false,
    impuesto: false,
    rol: false,
  },
};
